### ISSUE TITLE
[Fix] data.sql 실행이 hibernate가 스키마 생성한 뒤에 실행되도록 수정

### ISSUE THREAD

**Issue by mingsound21** [snack-exercise/snack-exercise-server#57]
## ⚠ 버그 내용
data.sql 파일로 더미데이터를 넣을 수 있다.
그런데 ddl-auto : create로 설정해두니 data.sql이 실행되고 나서 table create문이 실행되기에 더미데이터가 insert되지 않는 문제가 발생했다.

**Comment by mingsound21** [comment]
spring 2.5 버전 이상에서는 data.sql 스크립트는 Hibernate가 초기화되기 전에 실행된다고 한다. 
따라서 data.sql을 사용하여 Hibernate에 의해 생성된 스키마를 채우려면 spring.jpa.defer-datasource-initialization을 true로 설정해야한다.

```yml
 spring:
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    defer-datasource-initialization: true -> 추가

  sql:
    init:
      mode: always  -> 추가
```
